### ISSUE TITLE
Install drizzle

### ISSUE THREAD

**Issue by Minion3665** [TransGG/TransForm#1]
```[tasklist]
### Tasks
- [ ] https://github.com/TransGG/TransForm/issues/2
- [x] Install drizzle ORM
- [ ] Type up data model as decided on
- [ ] Create a database for testing
```
